infobox_to_pid:
  "cónyuge": "P26"
  "hijos": "P40"
  "partido": "P102"
  "ocupación": "P106"
  "premios": "P166"
  "lugar de nacimiento": "P19"
  "lugar de fallecimiento": "P20"
  "alma máter": "P69"
  "empleador": "P108"
  "cargo": "P39"
  "miembro de": "P463"
  "influenciado por": "P737"
